### ISSUE TITLE
Not work

### ISSUE THREAD

**Issue by michaelpeterlee** [azu/shallow-equal-object#2]
Returns false for our object. JSON.stringify() returns true.

![image](https://user-images.githubusercontent.com/19398181/43232892-45a4ff4c-90c7-11e8-9e24-92e961775a1d.png)

**Comment by azu** [comment]
Please tell me the result of `objectA.right === objectB.right`?
If the result is `false`, `shallow-equal-object` should return `false` by design.

FYI: `JSON.stringify` is different logic with shallow-equal.
`JSON.stringify` is deep-equal and ignore the difference of object.

```js
// "[]" === "[]"
JSON.stringify([]) === JSON.stringify([]); // => true
// `[]` (new array) is not strict equal with `[]` (new array)
shallow-equal-object([], []); // => false
```

- [Equality comparisons and sameness - JavaScript | MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Equality_comparisons_and_sameness)

**Comment by michaelpeterlee** [comment]
Re: https://github.com/azu/shallow-equal-props We seek a drop-in replacement for JSON.stringify() in shouldComponentUpdate(); this evaluates identical object structures as false, which is not what I was expecting.

**Comment by michaelpeterlee** [comment]
Re: https://github.com/azu/avoid-json-stringify-on-react

I arrived here to debug your example illustrating it's use in a React project to replace JSON.stringify() in Redux projects.

This project evaluates if same object instance, which is not suitable for immutable/Redux projects.

Sorry if I've posted to the wrong repo.

**Comment by michaelpeterlee** [comment]
Re: https://github.com/azu/avoid-json-stringify-on-react

Just to assert that the article that pointed me here is misleading. This indeed works correctly as you would expect from a shallow-equal evaluation.

I kindly suggest you amend docs on 'avoid-json-stringify-on-react' repo to assert comparison of a monolithic state object.
